name: "VCPKG (libexpat)"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '19 23 * * 5'

jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - os: ubuntu-20.04
          vcpkg_triplet: x64-linux-release
        - os: ubuntu-20.04
          vcpkg_triplet: x86-linux-release
        - os: macos-11
          vcpkg_triplet: x64-osx-release
        - os: macos-11
          vcpkg_triplet: x86-osx-release
        - os: windows-2019
          vcpkg_triplet: x64-windows-release
        - os: windows-2019
          vcpkg_triplet: x86-windows-release
    steps:
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: expat
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true