name: "VCPKG (libexpat)"

on: workflow_dispatch

jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        
        - os: ubuntu-20.04
          vcpkg_triplet: x64-linux-dynamic
          
        - os: macos-11
          vcpkg_triplet: x64-osx-dynamic
          
        - os: windows-2019
          vcpkg_triplet: x64-windows-release
          
        - os: windows-latest
          vcpkg_triplet: x64-windows-release
          
    steps:
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: expat
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true
      
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.config.vcpkg_triplet }}-${{ matrix.config.os }}
          path: ${{ github.workspace }}/vcpkg/installed/${{ matrix.config.vcpkg_triplet }}
          if-no-files-found: warn
          overwrite: true